# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dosirak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dosirak

  target 'DosirakTests' do
    inherit! :search_paths
    pod 'SnapKit'
    pod 'FSCalendar'

    # Pods for testing
  end

  target 'DosirakUITests' do
    # Pods for testing
  end

end
